name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run:  pip install -r requirements.txt
              pip install pytest
      - name: Install django-junit-report
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests and generate report
        run:  |
         pytest --junitxml=test-results.xml
         
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results.xml
